### ISSUE TITLE
ELK stack container, docker run instruction can't find 

### ISSUE THREAD

**Issue by jayramr** [irods/contrib#41] opened 2024-05-10 15:19 UTC
Hello, 

I tried to follow this https://github.com/irods/contrib/tree/main/irods_audit_elk_stack and build the container, but unfortunately I'm unable to find the steps  how to run this docker image.

If I simply run below, it is starting all the services, but this exposed within the container. Actually i need to map the ports with the host. 
```
docker run <image-name>
```

Also I'm looking for the steps how to configure  the audit plugin in  /etc/irods/server_config.json. I installed this pacakge "irods-rule-engine-plugin-audit-amqp" on the irods server which is running 4.3.1. 

Or for the irods audit configuration, do i need to follow the steps from this article https://slides.com/irods/ugm2018-getting-started ?

Please let me know. 

Thanks
Jay

**Comment by trel** [comment] 2024-05-10 15:23
This elk stack is for demo / training purposes - please don't use it for anything other than playing / learning.

You are correct about the port mapping - you can see how we stand it up in slides 7-10...
https://slides.com/irods/ugm2024-getting-started/#/7

The audit repository itself has some configuration information - but i'm noticing it might need a little update...
https://github.com/irods/irods_rule_engine_plugin_audit_amqp?tab=readme-ov-file#configuration

The getting started slides in the first link have been updated in the last couple days as we prepare for UGM2024 at the end of this month.

**Comment by jayramr** [comment] 2024-05-10 17:27
Thanks @trel i tried to setup this and for me there are no errors. 

But on the dashboard, i haven't received any graph and it shows "No results found".

I initiated iput/iget operation and waited for 30 mins and manually refreshed still no luck.

Please advise.

**Comment by trel** [comment] 2024-05-10 17:47
Make sure you are sending the right PEPs..
```
                     "pep_regex_to_match" : "audit_pep_(api|resource)_.*"
```

**Comment by jayramr** [comment] 2024-05-10 18:03
Yes @trel this is i followed. 

I'm getting the messages in the "Discover" tab. But in the iRODS Dashboard show "No results found".

**Comment by trel** [comment] 2024-05-10 18:06
So iRODS is configured correctly - and the messages are being captured by the broker - and retrieved and inserted into Elasticsearch... but Kibana dashboard isn't showing them correctly?

Try slides 7-10 from my link above again... it has been tested in the last 24h to populate the dashboard.

**Comment by jayramr** [comment] 2024-05-10 18:25
Yes I cross checked again, same configuration, still not sure why kibana not updation. 

I fetch the kibana.log from the container for your reference. Maybe this helps. 

[kibana.log](https://github.com/irods/contrib/files/15278653/kibana.log)

**Comment by trel** [comment] 2024-05-10 18:33
Not sure...

the only errors I see in there do mention a parser though...

```
{"service":{"node":{"roles":["background_tasks","ui"]}},"ecs":{"version":"8.11.0"},"@timestamp":"2024-05-10T17:50:58.257+00:00","message":"Failed to initialize service: parse_exception\n\tRoot causes:\n\t\tparse_exception: No processor type exists with name [inference]","log":{"level":"ERROR","logger":"plugins.observabilityAIAssistant.service"},"process":{"pid":959,"uptime":30.26180538},"trace":{"id":"a45ef6e5f828c039e192265a8c1f4aaf"},"transaction":{"id":"6cc401df8bb5ead1"}}
{"service":{"node":{"roles":["background_tasks","ui"]}},"ecs":{"version":"8.11.0"},"@timestamp":"2024-05-10T17:50:58.258+00:00","message":"Could not index 7 entries because of an initialisation error","log":{"level":"ERROR","logger":"plugins.observabilityAIAssistant.service"},"process":{"pid":959,"uptime":30.262464175},"trace":{"id":"a45ef6e5f828c039e192265a8c1f4aaf"},"transaction":{"id":"6cc401df8bb5ead1"}}
{"service":{"node":{"roles":["background_tasks","ui"]}},"ecs":{"version":"8.11.0"},"@timestamp":"2024-05-10T17:50:58.258+00:00","message":"parse_exception\n\tRoot causes:\n\t\tparse_exception: No processor type exists with name [inference]","error":{"message":"parse_exception\n\tRoot causes:\n\t\tparse_exception: No processor type exists with name [inference]","type":"ResponseError","stack_trace":"ResponseError: parse_exception\n\tRoot causes:\n\t\tparse_exception: No processor type exists with name [inference]\n    at KibanaTransport.request (/usr/share/kibana/node_modules/@elastic/transport/lib/Transport.js:479:27)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at KibanaTransport.request (/usr/share/kibana/node_modules/@kbn/core-elasticsearch-client-server-internal/src/create_transport.js:51:16)\n    at Ingest.putPipeline (/usr/share/kibana/node_modules/@elastic/elasticsearch/lib/api/api/ingest.js:139:16)\n    at ObservabilityAIAssistantService.<anonymous> (/usr/share/kibana/node_modules/@kbn/observability-ai-assistant-plugin/server/service/index.js:120:9)"},"log":{"level":"ERROR","logger":"plugins.observabilityAIAssistant.service"},"process":{"pid":959,"uptime":30.264763753},"trace":{"id":"a45ef6e5f828c039e192265a8c1f4aaf"},"transaction":{"id":"6cc401df8bb5ead1"}}
```

**Comment by alanking** [comment] 2024-05-13 15:38
I saw this as well, and it had to do with the not-logstash layer needing a tweak which has now been merged. In order to fix the issue, I had to remove the Docker image and all of its constituent layers up to and including the not-logstash layer so that the layers are pulled down correctly. Or, if you are building it yourself, make sure to build with `--no-cache` to ensure that the layer is rebuilt.

I saw this work after those changes were applied.

**Comment by alanking** [comment] 2024-05-13 22:00
Specifically, this is the one I had success with: https://hub.docker.com/layers/swooshycueb/irods-elk-stack/test1/images/sha256-404571d679fbfbea5bfa4fe59e96581351c521a91360304a56dcf0cd49ca5ae

**Comment by jayramr** [comment] 2024-05-15 07:21
Hi @alanking thanks for the update. 
I tried the image advised by you,  but still no results in the iRODS dashboard.

**Comment by alanking** [comment] 2024-05-15 14:22
Okay, can you please share the contents of `/etc/irods/server_config.json`? I'm specifically interested in the `/plugin_configuration/rule_engines` stanza.

**Comment by jayramr** [comment] 2024-05-16 06:28
Hi @alanking i uploaded the entire conf for your review. 
[Uploading server_config.json…]()

**Comment by alanking** [comment] 2024-05-16 13:57
Hmm... that link is back to this issue rather than a config file. Please try again

**Comment by jayramr** [comment] 2024-05-16 17:43
i tried again, with the same image https://hub.docker.com/layers/swooshycueb/irods-elk-stack/test1/images/sha256-404571d679fbfbea5bfa4fe59e96581351c521a91360304a56dcf0cd49ca5ae still no luck

**Comment by alanking** [comment] 2024-05-16 21:14
Sorry, by "try again" I was referring to the uploading of the server_config.json file. The link provided in your previous post appears to just link back to this issue.

So, please try uploading the server_config.json file again so we can see the configuration and maybe that can help.

**Comment by jayramr** [comment] 2024-05-21 06:50
[server_config_json.txt](https://github.com/irods/contrib/files/15385689/server_config_json.txt)

Please find the server_config.json file attached.

**Comment by trel** [comment] 2024-05-21 12:43
we've now updated the `pep_regex_to_match`... and removed the need for the `audit_` namespace...

the slides are up to date and are working for us.

**Comment by jayramr** [comment] 2024-05-23 06:22
Hi @alanking actually I'm following your latest slide only. I suspect why the dashboard are not updating because I used irods only for keeping file/directory metadata without uploading the real data into iRODS data grid.

I tested as per below 

1. Followed slide page from 7 till 12. 
2. Updated server_config.json and match as per slide
3. Docker run command as follows 
```
docker run -d -p 8080:15672 -p 5672:5672 -p 80:5601 -p 9201:9200  --name irods_elk irods/irods_audit_elk_stack
```
4. Launch kibana application on browser.
5. Able to see the AMQP messages on the Discover tab. 
6. I did some iput/iget operations. 
7. Then monitored the iRODS dashboard for any update. Still shows "No results found"


Thanks 
Jay

**Comment by jayramr** [comment] 2024-05-24 16:38
Hi @alanking i tested with the latest image and even retried again still no luck.

**Comment by Venustiano** [comment] 2024-07-09 08:57
Hello,

Is there any progress on this?

I only see activity when the container starts but then, I can not see activity when I run iRODS commands.

![image](https://github.com/irods/contrib/assets/39260912/d66fa20f-30f8-43f1-b99b-2d0c058d996a)

I can also see activity in rabbitmq (I assume that rabbitmq gets the iRODS messages)

![image](https://github.com/irods/contrib/assets/39260912/e1b2e2a8-0c72-4567-a58e-e4f81314700d)

It seems that the no-logstahs script is missing the messages from rabbitmq or failing to send them to elasticsearch.

I also tried to rebuild the container but I get the following errors

```
1.756 Hit:6 https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu noble InRelease
1.792 Reading package lists...
2.154 Reading package lists...
2.161 Building dependency tree...
2.228 Reading state information...
2.261 Some packages could not be installed. This may mean that you have
2.261 requested an impossible situation or if you are using the unstable
2.261 distribution that some required packages have not yet been created
2.261 or been moved out of Incoming.
2.261 The following information may help to resolve the situation:
2.261 
2.261 The following packages have unmet dependencies:
2.306  rabbitmq-server : Depends: erlang-base (>= 1:26.0) but 1:25.3.2.8+dfsg-1ubuntu4 is to be installed or
2.306                             erlang-base-hipe (>= 1:26.0) but it is not installable or
2.306                             esl-erlang (>= 1:26.0) but it is not installable
2.306                    Depends: erlang-crypto (>= 1:26.0) but 1:25.3.2.8+dfsg-1ubuntu4 is to be installed or
2.306                             esl-erlang (>= 1:26.0) but it is not installable
2.306                    Depends: erlang-eldap (>= 1:26.0) but 1:25.3.2.8+dfsg-1ubuntu4 is to be installed or
2.306                             esl-erlang (>= 1:26.0) but it is not installable
2.306                    Depends: erlang-inets (>= 1:26.0) but 1:25.3.2.8+dfsg-1ubuntu4 is to be installed or
2.306                             esl-erlang (>= 1:26.0) but it is not installable
2.306                    Depends: erlang-mnesia (>= 1:26.0) but 1:25.3.2.8+dfsg-1ubuntu4 is to be installed or
2.306                             esl-erlang (>= 1:26.0) but it is not installable
2.306                    Depends: erlang-os-mon (>= 1:26.0) but 1:25.3.2.8+dfsg-1ubuntu4 is to be installed or
2.306                             esl-erlang (>= 1:26.0) but it is not installable
2.306                    Depends: erlang-parsetools (>= 1:26.0) but 1:25.3.2.8+dfsg-1ubuntu4 is to be installed or
2.306                             esl-erlang (>= 1:26.0) but it is not installable
2.306                    Depends: erlang-public-key (>= 1:26.0) but 1:25.3.2.8+dfsg-1ubuntu4 is to be installed or
2.306                             esl-erlang (>= 1:26.0) but it is not installable
2.306                    Depends: erlang-runtime-tools (>= 1:26.0) but 1:25.3.2.8+dfsg-1ubuntu4 is to be installed or
2.306                             esl-erlang (>= 1:26.0) but it is not installable
2.306                    Depends: erlang-ssl (>= 1:26.0) but 1:25.3.2.8+dfsg-1ubuntu4 is to be installed or
2.306                             esl-erlang (>= 1:26.0) but it is not installable
2.306                    Depends: erlang-syntax-tools (>= 1:26.0) but 1:25.3.2.8+dfsg-1ubuntu4 is to be installed or
2.306                             esl-erlang (>= 1:26.0) but it is not installable
2.306                    Depends: erlang-tools (>= 1:26.0) but 1:25.3.2.8+dfsg-1ubuntu4 is to be installed or
2.306                             esl-erlang (>= 1:26.0) but it is not installable
2.306                    Depends: erlang-xmerl (>= 1:26.0) but 1:25.3.2.8+dfsg-1ubuntu4 is to be installed or
2.306                             esl-erlang (>= 1:26.0) but it is not installable
2.307 E: Unable to correct problems, you have held broken packages.
------
Dockerfile:81
--------------------
  80 |         echo "deb [signed-by=/usr/share/keyrings/rabbitmq_rabbitmq-server.gpg] https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/rabbitmq_rabbitmq-server.list
  81 | >>> RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
  82 | >>>     --mount=type=cache,target=/var/lib/apt,sharing=locked \
  83 | >>>     apt-get update && \
  84 | >>>     apt-get install -y \
  85 | >>>         rabbitmq-server -y --fix-missing \
  86 | >>>     && \
  87 | >>>     rm -rf /tmp/*
```

Do you have any suggestions to fix this?

Thank you in advance

**Comment by Venustiano** [comment] 2024-07-09 10:46
Looking at the `not-logstash` status, the service is down

```
docker exec -it rabbit /etc/init.d/not-logstash status
 * not-logstash is not running
```
but why?

**Comment by Venustiano** [comment] 2024-07-09 14:56
I did run `not-logstash` within the container and got the following error

```
{"@timestamp":1720535254218,"action":"STOP","hostname":"rdms-irods43","pid":4699}
__BEGIN_JSON__{"time_stamp": "1720535255579", "action": "START", "hostname": "rdms-pubirods", "pid": "2680"}__END_JSON__
Traceback (most recent call last):
  File "/var/lib/irods-elk/bin/not-logstash", line 151, in <module>
    sys.exit(_main())
             ^^^^^^^
  File "/var/lib/irods-elk/bin/not-logstash", line 147, in _main
    Container(ELKReader("localhost:5672", "audit_messages", args.workarounds)).run()
  File "/usr/lib/python3/dist-packages/proton/_reactor.py", line 197, in run
    while self.process():
          ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/proton/_reactor.py", line 260, in process
    event.dispatch(handler)
  File "/usr/lib/python3/dist-packages/proton/_events.py", line 161, in dispatch
    self.dispatch(h, type)
  File "/usr/lib/python3/dist-packages/proton/_events.py", line 161, in dispatch
    self.dispatch(h, type)
  File "/usr/lib/python3/dist-packages/proton/_events.py", line 158, in dispatch
    _dispatch(handler, type.method, self)
  File "/usr/lib/python3/dist-packages/proton/_events.py", line 129, in _dispatch
    m(*args)
  File "/usr/lib/python3/dist-packages/proton/_handlers.py", line 255, in on_delivery
    self.on_message(event)
  File "/usr/lib/python3/dist-packages/proton/_handlers.py", line 280, in on_message
    _dispatch(self.delegate, 'on_message', event)
  File "/usr/lib/python3/dist-packages/proton/_events.py", line 129, in _dispatch
    m(*args)
  File "/var/lib/irods-elk/bin/not-logstash", line 128, in on_message
    body_obj = json.loads(msg.body)
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

For some reason, the strings on the extremes of the message are not removed (`__BEGIN_JSON__`, `__END_JSON__`)

I added a new line to the `on_message` function (perhaps not ideal)

```
        def on_message(self, event):
                with self.id_ctr_lock:
                        msg_id = self.id_ctr
                        self.id_ctr += 1

                msg = event.message

                self.workaround_tokens(msg)

                msg.body = msg.body.replace("__BEGIN_JSON__","").replace("__END_JSON__", "") # new line

                # print(msg.body)

                body_obj = json.loads(msg.body)

                self.workaround_ts(body_obj)
                self.workaround_typing(body_obj)

                try:
                        self.es.index(
                                index = "irods_audit",
                                id = msg_id,
                                body = body_obj
                        )
                except Exception:
                        self.logger.exception('ES exception. body:\n%s', pformat(body_obj))

```
but seems to be working now
![image](https://github.com/irods/contrib/assets/39260912/850b0bd4-e477-4038-b989-ff9ce25febf4)

What would be an appropriate way to update this?
Could you also reproduce the errors I found when building the container?

**Comment by SwooshyCueb** [comment] 2024-07-09 15:23
I'll look into this today.

**Comment by SwooshyCueb** [comment] 2024-07-09 21:35
> For some reason, the strings on the extremes of the message are not removed (`__BEGIN_JSON__`, `__END_JSON__`)

Recent versions of the audit plugin do not add `__BEGIN_JSON__` and `__END_JSON__` to the AMQP messages, so `not-logstash` does not try to remove them by default.

The container entrypoint supports an arguments to turn on workarounds for older versions of the audit plugin if they are needed:
https://github.com/irods/contrib/blob/5e44ecf937c3e0e4137399d1e9fe72b1eff43202/irods_audit_elk_stack/README.md#entrypoint

> Could you also reproduce the errors I found when building the container?

Yes. RabbitMQ started building their packages against a newer version of erlang than was in the distro repos. I've opened #46 to address this.

**Comment by Venustiano** [comment] 2024-07-09 22:24
Hi @SwooshyCueb 

Thank you for your answers.

We are using ` irods-rule-engine-plugin-audit-amqp=4.3.2.0-0~bookworm `. 

Is there a more recent version?

**Comment by SwooshyCueb** [comment] 2024-07-10 00:44
> Hi @SwooshyCueb
> 
> Thank you for your answers.
> 
> We are using `irods-rule-engine-plugin-audit-amqp=4.3.2.0-0~bookworm`.
> 
> Is there a more recent version?

No, that is currently the most recent version.

The `__BEGIN_JSON__` and `__END_JSON__` tokens were removed starting with version 4.3.1.0.

Tomorrow, I will see if I can reproduce any of the other issues you have run into here.

**Comment by Venustiano** [comment] 2024-07-10 07:38
I found the problem, I had two iRODS instances running and one of them has an older version of the auditing plugin.

**Comment by alanking** [comment] 2024-07-10 14:23
@jayramr - Feel free to try out the PR at #46. It updates the rabbitmq packages and provides some more protections for the internal logic of not-logstash. Perhaps this will resolve the issues you're seeing. Sadly, I still have not been able to reproduce any issues with the image.

**Comment by SwooshyCueb** [comment] 2024-07-11 18:55
> I found the problem, I had two iRODS instances running and one of them has an older version of the auditing plugin.

I imagine this was the source of most (all?) of your problems with the prebuilt container. With #46, everything seems to be working fine as far as I can tell.

**Comment by Venustiano** [comment] 2024-07-11 20:47
> > I found the problem, I had two iRODS instances running and one of them has an older version of the auditing plugin.
> 
> I imagine this was the source of most (all?) of your problems with the prebuilt container. With #46, everything seems to be working fine as far as I can tell.

Yes, and with the latest changes in can also build the image.

**Comment by korydraughn** [comment] 2024-07-11 21:12
Excellent.

Closing as completed.

**Closed by korydraughn** 2024-07-11 21:12 UTC
